# GitHub Actions Virtual Environments
# https://github.com/actions/virtual-environments/

# A basic workflow intended for typical iOS and/or macOS apps

name: CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

env:
  WORKSPACE: PROJECT.xcworkspace
  SCHEME: PROJECT
  SCHEME_UNIT_TEST: PROJECT_UNIT
  SCHEME_UI_TEST: PROJECT_UI

  DEVELOPER_DIR: /Applications/Xcode_13.2.1.app/Contents/Developer

  IOS_SDK: iphonesimulator15.2
  IOS_DEST: "OS=15.2,name=iPhone 13 Mini"

  MACOS_SDK: macosx12.1
  MACOS_DEST: "arch=x86_64"

jobs:
  env-details:
    name: Environment details
    runs-on: macOS-11
    steps:
      - name: xcode version
        run: xcodebuild -version -sdk

      - name: list simulators
        run: |
          xcrun simctl delete unavailable
          xcrun simctl list

      - name: ruby versions
        run: |
          ruby --version
          gem --version
          bundler --version

  main:
    name: Build and Test
    runs-on: macOS-11
    steps:
      - name: git checkout
        uses: actions/checkout@v3

      # https://github.com/ruby/setup-ruby
      - name: ruby setup
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true

      - name: make
        run: make

      - name: iOS unit tests
        run: |
          set -o pipefail
          xcodebuild clean test \
            -workspace "$WORKSPACE" \
            -scheme "$SCHEME_UNIT_TEST" \
            -sdk "$IOS_SDK" \
            -destination "$IOS_DEST" \
            ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO | xcpretty -c

      - name: iOS ui tests
        run: |
          set -o pipefail
          xcodebuild clean test \
            -workspace "$WORKSPACE" \
            -scheme "$SCHEME_UI_TEST" \
            -sdk "$IOS_SDK" \
            -destination "$IOS_DEST" \
            ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO | xcpretty -c

      - name: macOS unit tests
        run: |
          set -o pipefail
          xcodebuild clean test \
            -workspace "$WORKSPACE" \
            -scheme "$SCHEME_UNIT_TEST" \
            -sdk "$MACOS_SDK" \
            -destination "$MACOS_DEST" \
            ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO | xcpretty -c

      - name: macOS ui tests
        run: |
          set -o pipefail
          xcodebuild clean test \
            -workspace "$WORKSPACE" \
            -scheme "$SCHEME_UI_TEST" \
            -sdk "$MACOS_SDK" \
            -destination "$MACOS_DEST" \
            ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO | xcpretty -c
