# GitHub Actions Virtual Environments
# https://github.com/actions/virtual-environments/

name: SwiftPM Integration

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

env:
  DEVELOPER_DIR: /Applications/Xcode_12.5.app/Contents/Developer

  IOS_SDK: iphonesimulator14.4
  IOS_DEST: "OS=14.4,name=iPhone 12 Mini"

  SCHEME: PROJECT

jobs:
  main:
    name: SwiftPM Build
    runs-on: macOS-11
    steps:
      - name: git checkout
        uses: actions/checkout@v2

      - name: xcode version
        run: xcodebuild -version -sdk

      - name: list simulators
        run: |
          xcrun simctl delete unavailable
          xcrun simctl list

      - name: generate xcodeproj
        run: swift package generate-xcodeproj

      - name: Build
        run: |
          set -o pipefail
          xcodebuild clean build -scheme "$SCHEME" -sdk "$IOS_SDK" -destination "$IOS_DEST" | xcpretty -c
